### ISSUE TITLE
CommonMark >=0.8.0 causes ModuleNotFoundError

### ISSUE THREAD

**Issue by mikelane** [Jc2k/pytest-markdown#2]
https://github.com/Jc2k/pytest-markdown/blob/41b73058d08f834cb7c37a59ed2263bfed2960ac/pyproject.toml#L11

```
  File "/Users/mike/.pyenv/versions/3.6.6/envs/pytest-lambda-venv/lib/python3.6/site-packages/pytest_markdown/plugin.py", line 5, in <module>
    import CommonMark
ModuleNotFoundError: No module named 'CommonMark'
```

Suggest you change your requirement to be `CommonMark~=0.7.5` instead of `CommonMark>=0.7.5`

**Comment by mikelane** [comment]
Alternatively, change the requirement to `CommonMark~=0.8.1` and in `plugin.py` do 

```import commonmark```

**Comment by Jc2k** [comment]
Hey @mikelane - thanks for the report! I've applied your suggested change in d4aa8d49bf4b50203479579744b67399d3cb3616, i'll try and get a release out ASAP.

**Comment by Jc2k** [comment]
Was reminded in another ticket that I had utterly failed to do a release so just have done one.
