### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by theY4Kman** [Jc2k/pytest-markdown#3]
Howdy again!

I'm working on increasing the pytest compatibility of my [pytest-lambda](https://github.com/theY4Kman/pytest-lambda) plugin, and I'm running into issues with later versions of pytest — that I see [you've fixed](https://github.com/Jc2k/pytest-markdown/commit/27975cbe1add89b08fa6b5f0898bd2b6c7fd10ca).

I've been using [poetry](https://github.com/sdispater/poetry) lately to handle reqs for new projects. It's lovely, but it's not great with handling git deps that don't have a setup.py or use poetry themselves — like pytest-markdown.

So, I've come to ask for a favour: would you publish a new version of pytest-markdown with your fixes to PyPI? I'll, uh, wash your car or something, idk.

**Comment by Jc2k** [comment]
Hi @theY4Kman 😄 I'll give it a go. It's been a while, let's see if i can remember how flit works!

**Comment by Jc2k** [comment]
Ok - release apparently uploaded, let me know how it goes.

**Comment by theY4Kman** [comment]
Daaaang, with the quickness! That did the trick. 

So, should I wax and buff it, too?

**Comment by Jc2k** [comment]
😆
