### ISSUE TITLE
Consider moving project under @pytest-dev organization

### ISSUE THREAD

**Issue by ssbarnea** [Jc2k/pytest-markdown#7]
As more and more pytest plugins are transferred under @pytest-dev, I would like to propose you to consider the same thing.

I already did this with at least 3 plugins and mainly because I want to lower the risks of them becoming unmaintained.

To initiate the process, you just open a ticket like https://github.com/pytest-dev/meta/issues/1 which allows others to evaluate proposal, which is more of a sanity check around licensing, CoC and stuff like this. The link i gave you is from one more problematic project due to its name, but even that one was sorted.

The official documentation about plugin adoption can be seen at https://docs.pytest.org/en/6.2.x/contributing.html#submitting-plugins-to-pytest-dev

**Comment by Jc2k** [comment]
As I'm not paid to work on either of my pytest plugins, it would certainly be a sensible thing to do. I'd certainly look at it if I wasn't able to do the bare minimum of maintenance any more or if any of my plugins were super popular and I couldn't keep up with the tickets and PR's. But i'm not there yet.

**Comment by ssbarnea** [comment]
The risks are real for any project having a single maintainer. Any of us could suddenly vanish (covid made me realise that more than ever), that is why I never host a project under my own account. At least I hope you do have a designated successor on https://github.com/settings/admin 

PS. You keep ownership over the repository, in fact other pytest members will not step-in unless you become unavailable. In fact that is how I ended up joining pytest, as a plugin author.

**Comment by Jc2k** [comment]
If this were `requests` i'd totally agree. But it's a 7 star plugin with 37 commits and 150 lines of code. I guess I just feel less passionate about it's value to the community than you 😆 Truthfully the main blocker is that I can't really be bothered with the busy work, and I don't really want to spend my spare time fighting with tox. If I thought it was a key plugin I would feel differently. If you submitted PR's to help meet the requirements and could handle most of the process on my behalf I wouldn't object.

(Ideally the tox.ini PR wouldn't infect my current development env or CI).
